/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wmscode;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author celstra31
 */
public class MyWindow extends javax.swing.JFrame {

    /**
     * Creates new form MyWindow
     */
    private Timer timer;

    public MyWindow() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtToken = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtVersion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDeviceId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lbLable = new javax.swing.JLabel();
        lbLable1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generate Code");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Token");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 100, 70, 25);

        txtToken.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtToken);
        txtToken.setBounds(100, 100, 170, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Version");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 80, 25);

        txtVersion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtVersion);
        txtVersion.setBounds(100, 70, 170, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Device Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 130, 70, 25);

        txtDeviceId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDeviceId.setText("c2235abe34e83bd4");
        jPanel1.add(txtDeviceId);
        txtDeviceId.setBounds(100, 130, 170, 25);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Generate Code");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 170, 200, 40);

        lbLable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLable.setText("Device Code");
        jPanel1.add(lbLable);
        lbLable.setBounds(60, 20, 180, 30);

        lbLable1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbLable1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbLable1);
        lbLable1.setBounds(50, 220, 190, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          String code=AppCode.getActivationCode(txtDeviceId.getText(), Integer.parseInt(txtToken.getText()), Integer.parseInt(txtVersion.getText()));
          lbLable1.setText(code);
          
    }//GEN-LAST:event_jButton1ActionPerformed

    int barzise = 0;
    String oldUrl = "";
    String newUrl = "";
    Set<String> set = new HashSet<String>();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        Dimension screnn = Toolkit.getDefaultToolkit().getScreenSize();
        int hei = screnn.height;
        int wid = screnn.width;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MyWindow m = new MyWindow();
                m.setBounds((wid-300)/2, (hei-300)/2, 300, 300);
                m.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbLable;
    private javax.swing.JLabel lbLable1;
    private javax.swing.JTextField txtDeviceId;
    private javax.swing.JTextField txtToken;
    private javax.swing.JTextField txtVersion;
    // End of variables declaration//GEN-END:variables
}
