/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xhtmlread;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author celstra31
 */
public class MyWindow extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form MyWindow
     */
    private Timer timer;
    private HtmlConv htmlConv;
    private List<String> excludeList;
    private List<String> tagsAndAttributs;
    private int lcType = 0;

    public MyWindow() {
        htmlConv = new HtmlConv();
        initComponents();
        excludeList = new ArrayList<>();
        excludeList.add("style");
        excludeList.add("script");

        tagsAndAttributs = new ArrayList<>();
        tagsAndAttributs.add("p:outputlabel=value");
        tagsAndAttributs.add("h:outputtext=value");
        tagsAndAttributs.add("p:column=headerText");
        tagsAndAttributs.add("f:selectitem=itemLabel");
        tagsAndAttributs.add("p:commandbutton=value");
        tagsAndAttributs.add("p:tab=title");
        tagsAndAttributs.add("p:dialog=header");

        txtSourceFolder.setText("E:\\html\\pages");
        txtDestinationFolder.setText("E:\\html\\CHANGE");
        txtPropfolder.setText("E:\\html");
        txtExtProps.setText("E:\\html\\Telugu\\message-te.properties");
        addExcludes();
        addTagsAndAttri();
        setLandList();
        jProHeader.setText("Files Convert");
        labFileWrite.setText("Waiting for property file creation");
        pnlExcludes.setVisible(false);
        pnlTagandAttri.setVisible(false);
        pnlFileChoser.setVisible(false);
        pnlSuccess.setVisible(false);
        jComboBox1.setSelectedItem("English");
        proStatus.setValue(0);
        timer = new Timer(10, new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                proStatus.setValue(htmlConv.getProgressCount());
                jProHeader.setText(proStatus.getValue()+"/"+proStatus.getMaximum()+" : "+htmlConv.getProText());
                proFileWrite.setMaximum(htmlConv.getTotalWords());
                proFileWrite.setValue(htmlConv.getProgressWordCount());
                labFileWrite.setText(proFileWrite.getValue()+"/"+proFileWrite.getMaximum()+" : "+htmlConv.getProWord());

            }
        });
    }

    public String[] listToArray(List<String> ls) {
        String[] a = new String[ls.size()];
        for (int i = 0; i < ls.size(); i++) {
            a[i] = ls.get(i);
        }
        return a;
    }

    public String[] setToArray(Set<String> st) {
        List<String> ls = new ArrayList<>();
        for (String s : st) {
            ls.add(s);
        }
        Collections.sort(ls);
        ls.add("Others");
        String[] a = new String[ls.size()];
        for (int i = 0; i < ls.size(); i++) {
            a[i] = ls.get(i);
        }
        return a;
    }

    public void addExcludes() {
        jlExcludes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = listToArray(excludeList);

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }

    public void addTagsAndAttri() {
        jlTagsAndAttri.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = listToArray(tagsAndAttributs);

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }

    public void setLandList() {
        Map<String, String> m = lanList();
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(setToArray(m.keySet())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlSuccess = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlFileChoser = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        pnlTagandAttri = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTag = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        btnAddEx1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtAttribute = new javax.swing.JTextField();
        pnlExcludes = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAddExclude = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        btnAddEx = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSourceFolder = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlExcludes = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        btnExcDelete = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlTagsAndAttri = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtDestinationFolder = new javax.swing.JTextField();
        btnExclAdd = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtPropfolder = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        txtOthers = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtExtProps = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        proStatus = new javax.swing.JProgressBar();
        jProHeader = new javax.swing.JLabel();
        labFileWrite = new javax.swing.JLabel();
        proFileWrite = new javax.swing.JProgressBar();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HTML Read");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        pnlSuccess.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlSuccess.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Process Completed Successfully");
        pnlSuccess.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlSuccess.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 160, 40));

        jPanel1.add(pnlSuccess);
        pnlSuccess.setBounds(160, 180, 300, 120);

        pnlFileChoser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        pnlFileChoser.add(jFileChooser1);

        jPanel1.add(pnlFileChoser);
        pnlFileChoser.setBounds(10, 100, 620, 390);

        pnlTagandAttri.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlTagandAttri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Add Tag and Attribute");
        pnlTagandAttri.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 190, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Tag");
        pnlTagandAttri.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, -1));

        txtTag.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pnlTagandAttri.add(txtTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 220, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("Close");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        pnlTagandAttri.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 80, -1));

        btnAddEx1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddEx1.setText("Add");
        btnAddEx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEx1ActionPerformed(evt);
            }
        });
        pnlTagandAttri.add(btnAddEx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 80, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Attibute");
        pnlTagandAttri.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, -1));

        txtAttribute.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pnlTagandAttri.add(txtAttribute, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 220, -1));

        jPanel1.add(pnlTagandAttri);
        pnlTagandAttri.setBounds(190, 200, 280, 210);

        pnlExcludes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlExcludes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Add Exclude");
        pnlExcludes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Exclude tag");
        pnlExcludes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtAddExclude.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pnlExcludes.add(txtAddExclude, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Close");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        pnlExcludes.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 80, -1));

        btnAddEx.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddEx.setText("Add");
        btnAddEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExActionPerformed(evt);
            }
        });
        pnlExcludes.add(btnAddEx, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 80, -1));

        jPanel1.add(pnlExcludes);
        pnlExcludes.setBounds(190, 200, 280, 210);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HTML Read");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 10, 400, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Exclude Tags");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 100, 170, 25);

        txtSourceFolder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtSourceFolder);
        txtSourceFolder.setBounds(180, 60, 390, 25);

        jlExcludes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlExcludes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlExcludes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jlExcludesAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jlExcludes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 130, 260, 120);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Source Folder");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 60, 110, 25);

        btnExcDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcDelete.setText("Delete");
        btnExcDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcDelete);
        btnExcDelete.setBounds(180, 260, 120, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("B");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(570, 60, 35, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tags = Attributes");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 100, 170, 25);

        jlTagsAndAttri.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlTagsAndAttri.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jlTagsAndAttri);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(350, 130, 260, 120);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(350, 260, 120, 25);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(490, 260, 120, 25);

        btnStart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnStart.setText("Start");
        btnStart.setToolTipText("");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart);
        btnStart.setBounds(500, 480, 120, 110);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Others");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(430, 310, 60, 25);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("B");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(570, 350, 35, 25);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("B");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(570, 400, 35, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Destination Folder");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 400, 150, 25);

        txtDestinationFolder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtDestinationFolder);
        txtDestinationFolder.setBounds(180, 400, 390, 25);

        btnExclAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExclAdd.setText("Add");
        btnExclAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExclAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnExclAdd);
        btnExclAdd.setBounds(40, 260, 120, 25);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Propert File Folder");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 440, 150, 25);

        txtPropfolder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtPropfolder);
        txtPropfolder.setBounds(180, 440, 390, 25);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("B");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(570, 440, 35, 25);

        txtOthers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtOthers);
        txtOthers.setBounds(500, 310, 100, 25);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Language");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 310, 80, 25);

        txtExtProps.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtExtProps);
        txtExtProps.setBounds(180, 350, 390, 25);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Existing Prop File");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 350, 150, 25);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Telugu", "Hindhi", "Others" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(180, 310, 200, 25);
        jComboBox1.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(proStatus);
        proStatus.setBounds(20, 510, 470, 20);

        jProHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(jProHeader);
        jProHeader.setBounds(20, 485, 470, 25);

        labFileWrite.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(labFileWrite);
        labFileWrite.setBounds(20, 540, 470, 25);
        jPanel1.add(proFileWrite);
        proFileWrite.setBounds(20, 565, 470, 20);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(30, 40, 580, 10);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        startConversion();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnExcDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcDeleteActionPerformed
        if (jlExcludes.getSelectedValue() != null) {
            excludeList.remove(jlExcludes.getSelectedValue());
            addExcludes();
        }
    }//GEN-LAST:event_btnExcDeleteActionPerformed

    private void btnExclAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExclAddActionPerformed
        pnlExcludes.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_btnExclAddActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        pnlExcludes.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnAddExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExActionPerformed
        if (txtAddExclude.getText() != null && txtAddExclude.getText().trim().length() > 0) {
            excludeList.add(txtAddExclude.getText().trim().toLowerCase());
            addExcludes();
            pnlExcludes.setVisible(false);
        }
    }//GEN-LAST:event_btnAddExActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        pnlTagandAttri.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnAddEx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEx1ActionPerformed
        if (txtTag.getText() != null && txtTag.getText().trim().length() > 0 && txtAttribute.getText() != null && txtAttribute.getText().trim().length() > 0) {
            tagsAndAttributs.add(txtTag.getText().trim().toLowerCase() + "=" + txtAttribute.getText().trim());
            addTagsAndAttri();
            pnlTagandAttri.setVisible(false);
        }
    }//GEN-LAST:event_btnAddEx1ActionPerformed

    private void jlExcludesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jlExcludesAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jlExcludesAncestorAdded

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        pnlTagandAttri.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (jlTagsAndAttri.getSelectedValue() != null) {
            tagsAndAttributs.remove(jlTagsAndAttri.getSelectedValue());
            addTagsAndAttri();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        if (jFileChooser1.getSelectedFile() != null) {
            if (lcType == 1) {
                txtSourceFolder.setText(jFileChooser1.getSelectedFile().getAbsolutePath());
            } else if (lcType == 2) {
                txtExtProps.setText(jFileChooser1.getSelectedFile().getAbsolutePath());
            } else if (lcType == 3) {
                txtDestinationFolder.setText(jFileChooser1.getSelectedFile().getAbsolutePath());
            } else if (lcType == 4) {
                txtPropfolder.setText(jFileChooser1.getSelectedFile().getAbsolutePath());
            }
            pnlFileChoser.setVisible(false);
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lcType = 1;
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        pnlFileChoser.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
        lcType = 2;
        pnlFileChoser.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        lcType = 3;
        pnlFileChoser.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        lcType = 4;
        pnlFileChoser.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        btnStart.setEnabled(true);
        pnlSuccess.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void startConversion() {
        btnStart.setEnabled(false);
        proStatus.setMaximum(htmlConv.getTotalNo(txtSourceFolder.getText(), getLanguage()));
        proStatus.setValue(0);
        jProHeader.setText("Start");
        proFileWrite.setMaximum(100);
        proFileWrite.setValue(0);
        labFileWrite.setText("Waiting");
        timer.start();
        Thread thread = new Thread(this);
        thread.start();

    }

    public void run() {
        if (true) {
            Map<String, String> tags = new HashMap<>();
            for (String s : tagsAndAttributs) {
                String[] s1 = s.split("=");
                tags.put(s1[0], s1[1]);
            }
            htmlConv.startProcess(txtSourceFolder.getText(),
                    getLanguage(), txtDestinationFolder.getText(), txtPropfolder.getText(), excludeList, tags, txtExtProps.getText());
            proStatus.setValue(proStatus.getMaximum());
            jProHeader.setText("Completed");
            proFileWrite.setValue(proFileWrite.getMaximum());
            labFileWrite.setText("Completed");
            timer.stop();
            pnlSuccess.setVisible(true);
        }
    }

    public String getLanguage() {
        if (jComboBox1.getSelectedItem() != null) {
            Map<String, String> m = lanList();
            if (m.containsKey(jComboBox1.getSelectedItem().toString())) {
                return m.get(jComboBox1.getSelectedItem().toString());
            } else {
                return txtOthers.getText();
            }
        }
        return "en";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        Dimension screnn = Toolkit.getDefaultToolkit().getScreenSize();
        int hei = screnn.height;
        int wid = screnn.width;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MyWindow m = new MyWindow();
                m.setBounds((wid - 650) / 2, (hei - 650) / 2, 650, 650);
                m.setVisible(true);
            }
        });
    }

    public Map<String, String> lanList() {
        Map<String, String> ll = new HashMap<>();
        ll.put("Afrikaans", "af");
        ll.put("Albanian", "sq");
        ll.put("Amharic", "am");
        ll.put("Arabic", "ar");
        ll.put("Armenian", "hy");
        ll.put("Assamese*", "as");
        ll.put("Aymara*", "ay");
        ll.put("Azerbaijani", "az");
        ll.put("Bambara*", "bm");
        ll.put("Basque", "eu");
        ll.put("Belarusian", "be");
        ll.put("Bengali", "bn");
        ll.put("Bhojpuri*", "bho");
        ll.put("Bosnian", "bs");
        ll.put("Bulgarian", "bg");
        ll.put("Catalan", "ca");
        ll.put("Cebuano", "ceb");
        ll.put("Corsican", "co");
        ll.put("Croatian", "hr");
        ll.put("Czech", "cs");
        ll.put("Danish", "da");
        ll.put("Dhivehi*", "dv");
        ll.put("Dogri*", "doi");
        ll.put("Dutch", "nl");
        ll.put("English", "en");
        ll.put("Esperanto", "eo");
        ll.put("Estonian", "et");
        ll.put("Ewe*", "ee");
        ll.put("Filipino (Tagalog)", "fil");
        ll.put("Finnish", "fi");
        ll.put("French", "fr");
        ll.put("Frisian", "fy");
        ll.put("Galician", "gl");
        ll.put("Georgian", "ka");
        ll.put("German", "de");
        ll.put("Greek", "el");
        ll.put("Guarani*", "gn");
        ll.put("Gujarati", "gu");
        ll.put("Haitian Creole", "ht");
        ll.put("Hausa", "ha");
        ll.put("Hawaiian", "haw");
        ll.put("Hebrew", "he");
        ll.put("Hindi", "hi");
        ll.put("Hmong", "hmn");
        ll.put("Hungarian", "hu");
        ll.put("Icelandic", "is");
        ll.put("Igbo", "ig");
        ll.put("Ilocano*", "ilo");
        ll.put("Indonesian", "id");
        ll.put("Irish", "ga");
        ll.put("Italian", "it");
        ll.put("Japanese", "ja");
        ll.put("Javanese", "jv");
        ll.put("Kannada", "kn");
        ll.put("Kazakh", "kk");
        ll.put("Khmer", "km");
        ll.put("Kinyarwanda", "rw");
        ll.put("Konkani*", "gom");
        ll.put("Korean", "ko");
        ll.put("Krio*", "kri");
        ll.put("Kurdish", "ku");
        ll.put("Kurdish (Sorani)*", "ckb");
        ll.put("Kyrgyz", "ky");
        ll.put("Lao", "lo");
        ll.put("Latin", "la");
        ll.put("Latvian", "lv");
        ll.put("Lingala*", "ln");
        ll.put("Lithuanian", "lt");
        ll.put("Luganda*", "lg");
        ll.put("Luxembourgish", "lb");
        ll.put("Macedonian", "mk");
        ll.put("Maithili*", "mai");
        ll.put("Malagasy", "mg");
        ll.put("Malay", "ms");
        ll.put("Malayalam", "ml");
        ll.put("Maltese", "mt");
        ll.put("Maori", "mi");
        ll.put("Marathi", "mr");
        ll.put("Meiteilon (Manipuri)*", "mni-Mtei");
        ll.put("Mizo*", "lus");
        ll.put("Mongolian", "mn");
        ll.put("Myanmar (Burmese)", "my");
        ll.put("Nepali", "ne");
        ll.put("Norwegian", "no");
        ll.put("Nyanja (Chichewa)", "ny");
        ll.put("Odia (Oriya)", "or");
        ll.put("Oromo*", "om");
        ll.put("Pashto", "ps");
        ll.put("Persian", "fa");
        ll.put("Polish", "pl");
        ll.put("Portuguese (Portugal, Brazil)", "pt");
        ll.put("Punjabi", "pa");
        ll.put("Quechua*", "qu");
        ll.put("Romanian", "ro");
        ll.put("Russian", "ru");
        ll.put("Samoan", "sm");
        ll.put("Sanskrit*", "sa");
        ll.put("Scots Gaelic", "gd");
        ll.put("Sepedi*", "nso");
        ll.put("Serbian", "sr");
        ll.put("Sesotho", "st");
        ll.put("Shona", "sn");
        ll.put("Sindhi", "sd");
        ll.put("Sinhala (Sinhalese)", "si");
        ll.put("Slovak", "sk");
        ll.put("Slovenian", "sl");
        ll.put("Somali", "so");
        ll.put("Spanish", "es");
        ll.put("Sundanese", "su");
        ll.put("Swahili", "sw");
        ll.put("Swedish", "sv");
        ll.put("Tagalog (Filipino)", "tl");
        ll.put("Tajik", "tg");
        ll.put("Tamil", "ta");
        ll.put("Tatar", "tt");
        ll.put("Telugu", "te");
        ll.put("Thai", "th");
        ll.put("Tigrinya*", "ti");
        ll.put("Tsonga*", "ts");
        ll.put("Turkish", "tr");
        ll.put("Turkmen", "tk");
        ll.put("Twi (Akan)*", "ak");
        ll.put("Ukrainian", "uk");
        ll.put("Urdu", "ur");
        ll.put("Uyghur", "ug");
        ll.put("Uzbek", "uz");
        ll.put("Vietnamese", "vi");
        ll.put("Welsh", "cy");
        ll.put("Xhosa", "xh");
        ll.put("Yiddish", "yi");
        ll.put("Yoruba", "yo");
        ll.put("Zulu", "zu");

        return ll;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEx;
    private javax.swing.JButton btnAddEx1;
    private javax.swing.JButton btnExcDelete;
    private javax.swing.JButton btnExclAdd;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jProHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> jlExcludes;
    private javax.swing.JList<String> jlTagsAndAttri;
    private javax.swing.JLabel labFileWrite;
    private javax.swing.JPanel pnlExcludes;
    private javax.swing.JPanel pnlFileChoser;
    private javax.swing.JPanel pnlSuccess;
    private javax.swing.JPanel pnlTagandAttri;
    private javax.swing.JProgressBar proFileWrite;
    private javax.swing.JProgressBar proStatus;
    private javax.swing.JTextField txtAddExclude;
    private javax.swing.JTextField txtAttribute;
    private javax.swing.JTextField txtDestinationFolder;
    private javax.swing.JTextField txtExtProps;
    private javax.swing.JTextField txtOthers;
    private javax.swing.JTextField txtPropfolder;
    private javax.swing.JTextField txtSourceFolder;
    private javax.swing.JTextField txtTag;
    // End of variables declaration//GEN-END:variables
}
