/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * ProductPanel.java
 *
 * Created on Jul 27, 2014, 11:22:02 AM
 */
package wms1.view;

import java.util.Arrays;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.JXDatePicker;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import wms1.dao.LoginDao;
import wms1.pojos.Settings;

import wms1.util.GeneralUtil;

/**
 *
 * @author SATISH SYAMALA
 */
public class ConfigurationPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductPanel
     */
    private HomePanel homePanel;
    private String menuName;
    private JXDatePicker fromDate;
    private JXDatePicker todateDate;
    private int page = 0;
    private int noRec = 0;
    private Settings settings;

    public ConfigurationPanel() {
        initComponents();
    }

    public void init(HomePanel homePanel, String menuName) {
        this.homePanel = homePanel;
        this.menuName = menuName;
        LoginDao ld = new LoginDao();
        settings = ld.getSettings();
        if (settings != null) {
            txtShopName.setText(settings.getShopName());
            txtMobileNo.setText(settings.getMobileNo());
            txtAddress.setText(settings.getAddress());
            txtFileLocation.setText(settings.getFileLocation());
            if (settings.getDiscounts() != null) {
                String s[] = settings.getDiscounts().split(",");
                int ind[] = new int[s.length];
                int inx = 0;
                for (String s1 : s) {
                    if (s1.equalsIgnoreCase("5")) {
                        ind[inx++] = 0;
                    } else if (s1.equalsIgnoreCase("10")) {
                        ind[inx++] = 1;
                    } else if (s1.equalsIgnoreCase("15")) {
                        ind[inx++] = 1;
                    } else if (s1.equalsIgnoreCase("20")) {
                        ind[inx++] = 1;
                    }
                }
                llstDiscount.setSelectedIndices(ind);
            }
        } else {
            settings = new Settings();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtShopName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtMobileNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        llstDiscount = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        txtFileLocation = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Discounts %");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(450, 100, 130, 30);

        txtShopName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtShopName);
        txtShopName.setBounds(170, 60, 250, 30);

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 204, 204));
        btnSearch.setText("Save");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch);
        btnSearch.setBounds(370, 440, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Mobile No.");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(450, 30, 100, 30);

        txtMobileNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtMobileNo);
        txtMobileNo.setBounds(450, 60, 240, 30);

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(170, 130, 250, 96);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Shop Name");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(170, 30, 130, 30);

        llstDiscount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        llstDiscount.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "5", "10", "15", "20" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(llstDiscount);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(450, 130, 240, 100);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Address");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(170, 100, 130, 30);

        txtFileLocation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtFileLocation);
        txtFileLocation.setBounds(170, 270, 250, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("File Location");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(170, 240, 130, 30);

        add(jPanel2);
        jPanel2.setBounds(0, 0, 790, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        settings.setShopName(txtShopName.getText().trim());
        settings.setAddress(txtAddress.getText().trim());
        settings.setMobileNo(txtMobileNo.getText().trim());
        settings.setFileLocation(txtFileLocation.getText().trim());
        List<String> s = llstDiscount.getSelectedValuesList();
        String dis = "";
        if (s != null && !s.isEmpty()) {
            for (String s1 : s) {
                dis += s1 + ",";
            }
        }
        if (dis.length() > 0) {
            dis = dis.substring(0, dis.length() - 1);
        }
        settings.setDiscounts(dis);
        LoginDao ld = new LoginDao();
        ld.saveSettings(settings);
        JOptionPane.showMessageDialog(this, "Saved successfully");
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> llstDiscount;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtFileLocation;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtShopName;
    // End of variables declaration//GEN-END:variables

}
