/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * ProductPanel.java
 *
 * Created on Jul 27, 2014, 11:22:02 AM
 */
package wms1.view;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdesktop.swingx.JXDatePicker;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import wms1.dao.BrandsDao;
import wms1.dao.ItemsDao;
import wms1.dao.LoginDao;
import wms1.pojos.Brands;
import wms1.pojos.Items;
import wms1.pojos.Purchases;
import wms1.pojos.PurchasesItems;
import wms1.pojos.Users;
import wms1.util.ExcelReadAndWrite;

import wms1.util.GeneralUtil;
import wms1.util.ReadCSV;

/**
 *
 * @author SATISH SYAMALA
 */
public class PurchasesPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductPanel
     */
    private HomePanel homePanel;
    private String menuName;
    private Map<String, Object> fieldsMap = new HashMap<String, Object>();
    private List<PurchasesItems> purchasesItemses;
    private int srNo;

    public PurchasesPanel() {
        initComponents();
    }

    public void init(HomePanel homePanel, String menuName) {

        pnlFilechosser.setVisible(false);
        GeneralUtil.setDailBound(pnlFilechosser, homePanel, 560, 400);
         lbTemplerHeaders1.setText("Brand, Code, Qty");
        this.homePanel = homePanel;
        this.menuName = menuName;
        ddBrand.setModel(new javax.swing.DefaultComboBoxModel(GeneralUtil.getBrandsArray("Select")));
        purchasesItemses = new ArrayList<>();
        srNo = 1;
        txtDate.setText(new SimpleDateFormat("dd-MM-yyyy").format(new Date()));
        showTableData();
    }

    public void showTableData() {
        Object[][] data = null;
        if (purchasesItemses != null && purchasesItemses.size() > 0) {
            data = new Object[purchasesItemses.size()][5];
            int i = 0;
            for (PurchasesItems p : purchasesItemses) {
                data[i][0] = p.getSrNo();
                data[i][1] = p.getItems().getBrandId().getBrandName();
                data[i][2] = p.getItems().getItemCode();
                data[i][3] = p.getItems().getItemName();
                data[i][4] = p.getQuantity();
                i++;
            }
        } else {
            data = new Object[0][0];
        }
        tbPurItems.setModel(new javax.swing.table.DefaultTableModel(
                data,
                new String[]{
                    "Sr.No", "Brand", "Item Code", "Name", "Quantity"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFilechosser = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        lbTemplerHeaders1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtQuantity = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lbDropDownVal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        ddBrand = new javax.swing.JComboBox();
        btnImport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPurItems = new javax.swing.JTable();
        lbDropDownVal1 = new javax.swing.JLabel();
        ddItems = new javax.swing.JComboBox();
        txtPurchaseNo = new javax.swing.JTextField();
        lbDropDownVal2 = new javax.swing.JLabel();
        btnSearch1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnImport2 = new javax.swing.JButton();
        labdate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        btnSearch2 = new javax.swing.JButton();
        btnImport3 = new javax.swing.JButton();

        pnlFilechosser.setTitle("Templet Headers (File :  CSV, XLS, XLSX)");
        pnlFilechosser.getContentPane().setLayout(null);

        jFileChooser1.setSelectedFile(new java.io.File("C:\\Program Files\\NetBeans-12.2\\csv"));
        jFileChooser1.setToolTipText("");
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        pnlFilechosser.getContentPane().add(jFileChooser1);
        jFileChooser1.setBounds(0, 30, 550, 350);

        lbTemplerHeaders1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTemplerHeaders1.setForeground(new java.awt.Color(0, 153, 255));
        lbTemplerHeaders1.setText("Templet Headers");
        pnlFilechosser.getContentPane().add(lbTemplerHeaders1);
        lbTemplerHeaders1.setBounds(20, 0, 490, 30);

        setOpaque(false);
        setLayout(null);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        txtQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQuantity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel2.add(txtQuantity);
        txtQuantity.setBounds(540, 420, 140, 30);

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 204, 204));
        btnSearch.setText("Add");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch);
        btnSearch.setBounds(690, 390, 80, 60);

        lbDropDownVal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal.setText("Brand");
        jPanel2.add(lbDropDownVal);
        lbDropDownVal.setBounds(120, 390, 70, 30);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(10, 470, 770, 10);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(10, 100, 770, 0);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText(" Purchase No");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 0, 110, 30);

        ddBrand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ddBrand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));
        ddBrand.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddBrandItemStateChanged(evt);
            }
        });
        ddBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddBrandActionPerformed(evt);
            }
        });
        jPanel2.add(ddBrand);
        ddBrand.setBounds(120, 420, 160, 30);

        btnImport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImport.setForeground(new java.awt.Color(204, 0, 0));
        btnImport.setText("Clear All");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });
        jPanel2.add(btnImport);
        btnImport.setBounds(20, 480, 150, 40);

        tbPurItems.setAutoCreateRowSorter(true);
        tbPurItems.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbPurItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Sr,No", "Brand", "Item Code", "Name", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPurItems.setFocusCycleRoot(true);
        tbPurItems.setOpaque(false);
        tbPurItems.setRowHeight(25);
        tbPurItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbPurItems.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbPurItems);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 770, 260);

        lbDropDownVal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal1.setText("Quantity");
        jPanel2.add(lbDropDownVal1);
        lbDropDownVal1.setBounds(540, 390, 70, 30);

        ddItems.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ddItems.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        ddItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddItemsActionPerformed(evt);
            }
        });
        jPanel2.add(ddItems);
        ddItems.setBounds(320, 420, 190, 30);

        txtPurchaseNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtPurchaseNo);
        txtPurchaseNo.setBounds(20, 30, 200, 30);

        lbDropDownVal2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal2.setText("Item");
        jPanel2.add(lbDropDownVal2);
        lbDropDownVal2.setBounds(320, 390, 70, 30);

        btnSearch1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch1.setForeground(new java.awt.Color(255, 0, 0));
        btnSearch1.setText("X row");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch1);
        btnSearch1.setBounds(10, 370, 80, 30);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(10, 530, 770, 10);

        btnImport2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImport2.setForeground(new java.awt.Color(255, 153, 0));
        btnImport2.setText("Import");
        btnImport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImport2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnImport2);
        btnImport2.setBounds(640, 480, 130, 40);

        labdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labdate.setText(" Date");
        jPanel2.add(labdate);
        labdate.setBounds(260, 0, 80, 30);

        txtDate.setEditable(false);
        txtDate.setBackground(new java.awt.Color(255, 255, 255));
        txtDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtDate);
        txtDate.setBounds(260, 30, 200, 30);

        btnSearch2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch2.setForeground(new java.awt.Color(0, 102, 51));
        btnSearch2.setText("Purachase List");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch2);
        btnSearch2.setBounds(20, 540, 180, 30);

        btnImport3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnImport3.setForeground(new java.awt.Color(0, 153, 51));
        btnImport3.setText("Create");
        btnImport3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImport3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnImport3);
        btnImport3.setBounds(610, 10, 140, 80);

        add(jPanel2);
        jPanel2.setBounds(0, 0, 790, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        addToCart();
    }//GEN-LAST:event_btnSearchActionPerformed
    public void addToCart() {
        boolean check = true;
        int qty = 0;
        if (ddItems.getSelectedItem() == null || ddItems.getSelectedItem().toString().equalsIgnoreCase("select")) {
            check = false;
            JOptionPane.showMessageDialog(this, "Please select Item");
        } else if (txtQuantity.getText() == null || txtQuantity.getText().trim().length() == 0) {
            check = false;
            JOptionPane.showMessageDialog(this, "Quantity Requred");
        } else {
            try {
                qty = Integer.parseInt(txtQuantity.getText().toString());
                if (qty <= 0) {
                    check = false;
                    JOptionPane.showMessageDialog(this, "Quantity should be greater than 0");
                }
            } catch (Exception e) {
                check = false;
                JOptionPane.showMessageDialog(this, "Invalid Quantity");
            }
        }
        if (check) {
            PurchasesItems p = new PurchasesItems();
            p.setSrNo(srNo++);
            String s[] = ddItems.getSelectedItem().toString().split("-");
            long itId = Long.parseLong(s[s.length - 1]);
            ItemsDao itmd = new ItemsDao();
            p.setItems(itmd.getItems(itId, null, null).get(0));
            p.setQuantity(qty);
            p.setPrice(p.getItems().getPrice());
            purchasesItemses.add(p);
            txtQuantity.setText("0");
            ddItems.setSelectedItem("Select");
            showTableData();
        }
    }

    private void ddBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddBrandActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        clearAll();
    }//GEN-LAST:event_btnImportActionPerformed

    public void clearAll() {
        purchasesItemses = new ArrayList<>();
        srNo = 1;
        showTableData();
    }

    private void ddItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddItemsActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        if (tbPurItems.getSelectedColumnCount() > 0) {
            int sr = Integer.parseInt(tbPurItems.getValueAt(tbPurItems.getSelectedRow(), 0).toString());
            for (int i = 0; i < purchasesItemses.size(); i++) {
                if (purchasesItemses.get(i).getSrNo() == sr) {
                    purchasesItemses.remove(i);
                    break;
                }
            }
            showTableData();
        } else {
            JOptionPane.showMessageDialog(this, "Please select row for delete");
        }
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnImport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImport2ActionPerformed
        pnlFilechosser.setVisible(true);
    }//GEN-LAST:event_btnImport2ActionPerformed

    private void ddBrandItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddBrandItemStateChanged
        if (ddBrand.getSelectedItem() != null && !ddBrand.getSelectedItem().toString().equalsIgnoreCase("select")) {
            ddItems.setModel(new javax.swing.DefaultComboBoxModel(GeneralUtil.getItemeArray("Select", ddBrand.getSelectedItem().toString())));
        } else {
            ddItems.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Select"}));
        }
    }//GEN-LAST:event_ddBrandItemStateChanged

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        this.homePanel.openPurcaseList(menuName);
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void btnImport3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImport3ActionPerformed

        if (txtPurchaseNo.getText() != null && txtPurchaseNo.getText().trim().length() > 0) {
            if (!purchasesItemses.isEmpty()) {
                Purchases p = new Purchases();
                p.setPurchaseNo(txtPurchaseNo.getText());
                p.setCreatedBy(homePanel.getMainWindow().getUsers().getUserId());
                p.setStatus("active");
                p.setCreatedOn(new Date());
                p.setPurchaseItems(purchasesItemses);
                ItemsDao id = new ItemsDao();
                String msg = id.savePurchases(p);
                if (msg.equalsIgnoreCase("success")) {
                    JOptionPane.showMessageDialog(this, "Saved Successfully");
                     this.homePanel.openPurcaseList(menuName);
                    clearAll();
                } else {
                    JOptionPane.showMessageDialog(this, msg);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please add Items");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Purchare No. Required");
        }

    }//GEN-LAST:event_btnImport3ActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed

        if (evt.getActionCommand().equalsIgnoreCase("ApproveSelection")) {
            if (jFileChooser1.getSelectedFile() != null) {
                System.err.println("File Path : " + jFileChooser1.getSelectedFile().getAbsolutePath());
                List<List<String>> data = null;
                String path = jFileChooser1.getSelectedFile().getAbsolutePath().toLowerCase();
                if (path.endsWith(".csv")) {
                    data = ReadCSV.readCSVFile(path);
                } else if (path.endsWith(".xls")) {
                    data = ExcelReadAndWrite.readXls(path);
                } else if (path.endsWith(".xlsx")) {
                    data = ExcelReadAndWrite.readXlsx(path);
                }
                if (data != null) {
                     if (!data.isEmpty() && data.size() > 1) {
                        ItemsDao id = new ItemsDao();
                        List<Items> ls = id.getItems(0, null, null);
                        Map<String, Items> itemMap = new HashMap<>();
                        for (Items it : ls) {
                            itemMap.put(it.getItemCode().toLowerCase(), it);
                        }
                        for (int i = 1; i < data.size(); i++) {
                            List<String> row = data.get(i);
                            System.out.println(row);
                            if (itemMap.containsKey(row.get(1).trim().toLowerCase())) {
                                PurchasesItems p = new PurchasesItems();
                                p.setSrNo(srNo++);
                                p.setItems(itemMap.get(row.get(1).trim().toLowerCase()));
                                p.setQuantity((int)Double.parseDouble(row.get(2)));
                                purchasesItemses.add(p);
                            }

                        }
                          System.out.println("purchasesItemses.size() "+purchasesItemses.size());
                        showTableData();
                        pnlFilechosser.setVisible(false);
                    }else{
                           JOptionPane.showMessageDialog(this, "No Data for import");
                     }

                } else {
                    JOptionPane.showMessageDialog(this, "Please chose CSV, Xls or Xlsx file");
                }
            }
        } else {
            pnlFilechosser.setVisible(false);
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnImport2;
    private javax.swing.JButton btnImport3;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JComboBox ddBrand;
    private javax.swing.JComboBox ddItems;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labdate;
    private javax.swing.JLabel lbDropDownVal;
    private javax.swing.JLabel lbDropDownVal1;
    private javax.swing.JLabel lbDropDownVal2;
    private javax.swing.JLabel lbTemplerHeaders1;
    private javax.swing.JDialog pnlFilechosser;
    private javax.swing.JTable tbPurItems;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPurchaseNo;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

}
