/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * ProductPanel.java
 *
 * Created on Jul 27, 2014, 11:22:02 AM
 */
package wms1.view;

import java.awt.print.PrinterException;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdesktop.swingx.JXDatePicker;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import wms1.dao.BrandsDao;
import wms1.dao.ItemsDao;
import wms1.dao.LoginDao;
import wms1.pojos.Brands;
import wms1.pojos.Items;
import wms1.pojos.Purchases;
import wms1.pojos.PurchasesItems;
import wms1.pojos.Sales;
import wms1.pojos.SalesItems;
import wms1.pojos.Users;

import wms1.util.GeneralUtil;
import wms1.util.OrderPDF;
import wms1.util.ReadCSV;

/**
 *
 * @author SATISH SYAMALA
 */
public class SalesPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form ProductPanel
     */
    private HomePanel homePanel;
    private String menuName;
    private Map<String, Object> fieldsMap = new HashMap<String, Object>();
    private List<SalesItems> salesItems;
    private int srNo;
    private Sales sales = null;
    private Items items = null;

    public SalesPanel1() {
        initComponents();
    }

    public void init(HomePanel homePanel, String menuName) {
        pnlConfirmation.setVisible(false);
        pnlAddItems.setVisible(false);
        pnlInvoice.setVisible(false);
        this.homePanel = homePanel;
        this.menuName = menuName;
        ddBrand.setModel(new javax.swing.DefaultComboBoxModel(GeneralUtil.getBrandsArray("Select")));
        ddIDiscount.setModel(new javax.swing.DefaultComboBoxModel(ReadCSV.getSettings().getDiscountArray()));
        GeneralUtil.setDailBound(pnlInvoice, homePanel, 680, 500);
        GeneralUtil.setDailBound(pnlConfirmation, homePanel, 480, 380);
         GeneralUtil.setDailBound(pnlAddItems, homePanel, 400, 550);
        salesItems = new ArrayList<>();
        srNo = 1;
        sales = new Sales();
        txtDate.setText(new SimpleDateFormat("dd-MM-yyyy").format(new Date()));
        clearAddFields();
        clearHeaderFields();
        showTableData();
    }

    public void showTableData() {
        Object[][] data = null;
        double tm = 0;
        double td = 0;
        double tfa = 0;
        if (salesItems != null && salesItems.size() > 0) {
            data = new Object[salesItems.size()][8];
            int i = 0;
            for (SalesItems p : salesItems) {
                data[i][0] = p.getSrNo();
                data[i][1] = p.getItems().getBrandId().getBrandName();
                data[i][2] = p.getItems().getItemName();
                data[i][3] = p.getQuantity();
                data[i][4] = p.getPrice();
                data[i][5] = p.getAmount();
                data[i][6] = p.getDiscount();
                data[i][7] = p.getTotalAmount();
                tm += p.getAmount();
                td += p.getDiscount();
                tfa += p.getTotalAmount();
                i++;
            }
        } else {
            data = new Object[0][0];
        }
        txtTotalAmt.setText(tm + "");
        txtTotalDisc.setText(td + "");
        txttotalFinalAmount.setText(tfa + "");
        tbPurItems.setModel(new javax.swing.table.DefaultTableModel(
                data,
                new String[]{
                    "Sr,No", "Brand", "Item", "Qty.", "Price", "Amount", "Discount", "Final Amt"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInvoice = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        htmlContent = new javax.swing.JTextPane();
        btnCSV4 = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        pnlAddItems = new javax.swing.JDialog();
        btnAddItemClose = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        lbDropDownVal10 = new javax.swing.JLabel();
        txtSerialNo = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        lbDropDownVal3 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lbDropDownVal4 = new javax.swing.JLabel();
        ddIDiscount = new javax.swing.JComboBox();
        lbDropDownVal6 = new javax.swing.JLabel();
        txtFinalAmount = new javax.swing.JTextField();
        lbDropDownVal5 = new javax.swing.JLabel();
        lbDropDownVal11 = new javax.swing.JLabel();
        btnAdditem1 = new javax.swing.JButton();
        lbDropDownVal12 = new javax.swing.JLabel();
        lbDropDownVal13 = new javax.swing.JLabel();
        lbDropDownVal15 = new javax.swing.JLabel();
        txtAddItemCode = new javax.swing.JTextField();
        txtAddItemName = new javax.swing.JTextField();
        txtAddItemBrand = new javax.swing.JTextField();
        lbDropDownVal16 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        pnlConfirmation = new javax.swing.JDialog();
        btnConfirm = new javax.swing.JButton();
        btnConfirmClose = new javax.swing.JButton();
        lbFnTot = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbItemCount = new javax.swing.JLabel();
        lbAmount = new javax.swing.JLabel();
        lbDisc = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabConfirmation = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        lbDropDownVal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ddBrand = new javax.swing.JComboBox();
        btnImport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPurItems = new javax.swing.JTable();
        ddItems = new javax.swing.JComboBox();
        txtMobileNo = new javax.swing.JTextField();
        lbDropDownVal2 = new javax.swing.JLabel();
        btnSearch1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        labdate = new javax.swing.JLabel();
        txtAddess = new javax.swing.JTextField();
        btnSearch2 = new javax.swing.JButton();
        btnImport3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnSearch3 = new javax.swing.JButton();
        lbDropDownVal7 = new javax.swing.JLabel();
        txtTotalAmt = new javax.swing.JTextField();
        lbDropDownVal8 = new javax.swing.JLabel();
        txtTotalDisc = new javax.swing.JTextField();
        lbDropDownVal9 = new javax.swing.JLabel();
        txttotalFinalAmount = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtCustName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        labdate1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        lbDropDownVal14 = new javax.swing.JLabel();
        txtBarCode = new javax.swing.JTextField();
        labdate2 = new javax.swing.JLabel();

        pnlInvoice.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                pnlInvoiceWindowDeactivated(evt);
            }
        });
        pnlInvoice.getContentPane().setLayout(null);

        htmlContent.setEditable(false);
        htmlContent.setContentType("text/html"); // NOI18N
        htmlContent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane3.setViewportView(htmlContent);

        pnlInvoice.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 10, 660, 350);

        btnCSV4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCSV4.setForeground(new java.awt.Color(204, 0, 0));
        btnCSV4.setText("Close");
        btnCSV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSV4ActionPerformed(evt);
            }
        });
        pnlInvoice.getContentPane().add(btnCSV4);
        btnCSV4.setBounds(140, 380, 190, 30);

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(0, 153, 102));
        btnPrint.setText("Prnit");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        pnlInvoice.getContentPane().add(btnPrint);
        btnPrint.setBounds(350, 380, 190, 30);

        pnlAddItems.setTitle("  Add Item");
        pnlAddItems.getContentPane().setLayout(null);

        btnAddItemClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddItemClose.setForeground(new java.awt.Color(204, 0, 0));
        btnAddItemClose.setText("Close");
        btnAddItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemCloseActionPerformed(evt);
            }
        });
        pnlAddItems.getContentPane().add(btnAddItemClose);
        btnAddItemClose.setBounds(60, 430, 140, 40);

        txtPrice.setEditable(false);
        txtPrice.setBackground(new java.awt.Color(255, 255, 255));
        txtPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pnlAddItems.getContentPane().add(txtPrice);
        txtPrice.setBounds(170, 180, 190, 30);

        lbDropDownVal10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal10.setText("Serial No.");
        pnlAddItems.getContentPane().add(lbDropDownVal10);
        lbDropDownVal10.setBounds(60, 140, 70, 30);

        txtSerialNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSerialNo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pnlAddItems.getContentPane().add(txtSerialNo);
        txtSerialNo.setBounds(170, 140, 190, 30);

        txtQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQuantity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantityFocusLost(evt);
            }
        });
        pnlAddItems.getContentPane().add(txtQuantity);
        txtQuantity.setBounds(170, 220, 190, 30);

        lbDropDownVal3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal3.setText("Quantity *");
        pnlAddItems.getContentPane().add(lbDropDownVal3);
        lbDropDownVal3.setBounds(60, 220, 100, 30);

        txtAmount.setEditable(false);
        txtAmount.setBackground(new java.awt.Color(255, 255, 255));
        txtAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pnlAddItems.getContentPane().add(txtAmount);
        txtAmount.setBounds(170, 260, 190, 30);

        lbDropDownVal4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal4.setText("Amount");
        pnlAddItems.getContentPane().add(lbDropDownVal4);
        lbDropDownVal4.setBounds(60, 260, 70, 30);

        ddIDiscount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ddIDiscount.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        ddIDiscount.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddIDiscountItemStateChanged(evt);
            }
        });
        ddIDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddIDiscountActionPerformed(evt);
            }
        });
        pnlAddItems.getContentPane().add(ddIDiscount);
        ddIDiscount.setBounds(170, 300, 190, 30);

        lbDropDownVal6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal6.setText("Discount");
        pnlAddItems.getContentPane().add(lbDropDownVal6);
        lbDropDownVal6.setBounds(60, 300, 80, 30);

        txtFinalAmount.setEditable(false);
        txtFinalAmount.setBackground(new java.awt.Color(255, 255, 255));
        txtFinalAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFinalAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pnlAddItems.getContentPane().add(txtFinalAmount);
        txtFinalAmount.setBounds(170, 380, 190, 30);

        lbDropDownVal5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal5.setText("Final Amt");
        pnlAddItems.getContentPane().add(lbDropDownVal5);
        lbDropDownVal5.setBounds(60, 380, 70, 30);

        lbDropDownVal11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal11.setText("Price");
        pnlAddItems.getContentPane().add(lbDropDownVal11);
        lbDropDownVal11.setBounds(60, 180, 40, 30);

        btnAdditem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdditem1.setForeground(new java.awt.Color(0, 204, 204));
        btnAdditem1.setText("Add");
        btnAdditem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdditem1ActionPerformed(evt);
            }
        });
        pnlAddItems.getContentPane().add(btnAdditem1);
        btnAdditem1.setBounds(220, 430, 150, 40);

        lbDropDownVal12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal12.setText("Brand");
        pnlAddItems.getContentPane().add(lbDropDownVal12);
        lbDropDownVal12.setBounds(60, 20, 80, 30);

        lbDropDownVal13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal13.setText("Item Code");
        pnlAddItems.getContentPane().add(lbDropDownVal13);
        lbDropDownVal13.setBounds(60, 60, 90, 30);

        lbDropDownVal15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal15.setText("Item Name");
        pnlAddItems.getContentPane().add(lbDropDownVal15);
        lbDropDownVal15.setBounds(60, 100, 90, 30);

        txtAddItemCode.setEditable(false);
        txtAddItemCode.setBackground(new java.awt.Color(255, 255, 255));
        txtAddItemCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAddItemCode.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAddItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddItemCodeActionPerformed(evt);
            }
        });
        pnlAddItems.getContentPane().add(txtAddItemCode);
        txtAddItemCode.setBounds(170, 60, 190, 30);

        txtAddItemName.setEditable(false);
        txtAddItemName.setBackground(new java.awt.Color(255, 255, 255));
        txtAddItemName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAddItemName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAddItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddItemNameActionPerformed(evt);
            }
        });
        pnlAddItems.getContentPane().add(txtAddItemName);
        txtAddItemName.setBounds(170, 100, 190, 30);

        txtAddItemBrand.setEditable(false);
        txtAddItemBrand.setBackground(new java.awt.Color(255, 255, 255));
        txtAddItemBrand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAddItemBrand.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAddItemBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddItemBrandActionPerformed(evt);
            }
        });
        pnlAddItems.getContentPane().add(txtAddItemBrand);
        txtAddItemBrand.setBounds(170, 20, 190, 30);

        lbDropDownVal16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal16.setText("Discount");
        pnlAddItems.getContentPane().add(lbDropDownVal16);
        lbDropDownVal16.setBounds(60, 340, 70, 30);

        txtDiscount.setEditable(false);
        txtDiscount.setBackground(new java.awt.Color(255, 255, 255));
        txtDiscount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDiscount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pnlAddItems.getContentPane().add(txtDiscount);
        txtDiscount.setBounds(170, 340, 190, 30);

        pnlConfirmation.setTitle("Sales Confirmation");
        pnlConfirmation.getContentPane().setLayout(null);

        btnConfirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(0, 153, 0));
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        pnlConfirmation.getContentPane().add(btnConfirm);
        btnConfirm.setBounds(260, 290, 130, 40);

        btnConfirmClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConfirmClose.setForeground(new java.awt.Color(255, 0, 0));
        btnConfirmClose.setText("Close");
        btnConfirmClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmCloseActionPerformed(evt);
            }
        });
        pnlConfirmation.getContentPane().add(btnConfirmClose);
        btnConfirmClose.setBounds(110, 290, 130, 40);

        lbFnTot.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbFnTot.setForeground(new java.awt.Color(0, 153, 0));
        lbFnTot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbFnTot.setText("0");
        pnlConfirmation.getContentPane().add(lbFnTot);
        lbFnTot.setBounds(260, 240, 110, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Discount        :");
        pnlConfirmation.getContentPane().add(jLabel11);
        jLabel11.setBounds(130, 210, 130, 30);

        lbItemCount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbItemCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbItemCount.setText("2");
        pnlConfirmation.getContentPane().add(lbItemCount);
        lbItemCount.setBounds(90, 20, 40, 30);

        lbAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbAmount.setText("0");
        pnlConfirmation.getContentPane().add(lbAmount);
        lbAmount.setBounds(260, 180, 110, 30);

        lbDisc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDisc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDisc.setText("0");
        pnlConfirmation.getContentPane().add(lbDisc);
        lbDisc.setBounds(260, 210, 110, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Invoice Amt  :");
        pnlConfirmation.getContentPane().add(jLabel15);
        jLabel15.setBounds(130, 240, 130, 30);

        tabConfirmation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item", "Quantity", "Discount", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabConfirmation);

        pnlConfirmation.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 50, 470, 120);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Amount         :");
        pnlConfirmation.getContentPane().add(jLabel16);
        jLabel16.setBounds(130, 180, 130, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Items  :");
        pnlConfirmation.getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 20, 60, 30);

        setOpaque(false);
        setLayout(null);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 204, 204));
        btnSearch.setText("Add");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch);
        btnSearch.setBounds(580, 400, 190, 70);

        lbDropDownVal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal.setText("Brand");
        jPanel2.add(lbDropDownVal);
        lbDropDownVal.setBounds(30, 380, 70, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mobile No. *");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(250, 0, 120, 30);

        ddBrand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ddBrand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));
        ddBrand.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddBrandItemStateChanged(evt);
            }
        });
        ddBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddBrandActionPerformed(evt);
            }
        });
        jPanel2.add(ddBrand);
        ddBrand.setBounds(30, 410, 220, 30);

        btnImport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImport.setForeground(new java.awt.Color(204, 0, 0));
        btnImport.setText("Clear All");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });
        jPanel2.add(btnImport);
        btnImport.setBounds(670, 480, 100, 40);

        tbPurItems.setAutoCreateRowSorter(true);
        tbPurItems.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbPurItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Sr,No", "Brand", "Item", "Qty.", "Price", "Amount", "Discount", "Final Amt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPurItems.setFocusCycleRoot(true);
        tbPurItems.setOpaque(false);
        tbPurItems.setRowHeight(25);
        tbPurItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbPurItems.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbPurItems);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 770, 180);

        ddItems.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ddItems.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        ddItems.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddItemsItemStateChanged(evt);
            }
        });
        ddItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddItemsActionPerformed(evt);
            }
        });
        jPanel2.add(ddItems);
        ddItems.setBounds(280, 410, 290, 30);

        txtMobileNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtMobileNo);
        txtMobileNo.setBounds(250, 30, 190, 30);

        lbDropDownVal2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal2.setText("     OR");
        jPanel2.add(lbDropDownVal2);
        lbDropDownVal2.setBounds(250, 445, 90, 30);

        btnSearch1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch1.setForeground(new java.awt.Color(255, 0, 0));
        btnSearch1.setText("Clear");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch1);
        btnSearch1.setBounds(580, 480, 80, 40);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(10, 130, 770, 10);

        labdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labdate.setText("Address");
        jPanel2.add(labdate);
        labdate.setBounds(250, 60, 80, 30);

        txtAddess.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtAddess);
        txtAddess.setBounds(250, 90, 190, 30);

        btnSearch2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch2.setForeground(new java.awt.Color(0, 102, 51));
        btnSearch2.setText("Sales List");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch2);
        btnSearch2.setBounds(10, 540, 180, 40);

        btnImport3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnImport3.setForeground(new java.awt.Color(0, 153, 51));
        btnImport3.setText("Create");
        btnImport3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImport3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnImport3);
        btnImport3.setBounds(580, 20, 150, 90);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(10, 530, 770, 10);

        btnSearch3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch3.setForeground(new java.awt.Color(255, 0, 0));
        btnSearch3.setText("X Row");
        btnSearch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch3);
        btnSearch3.setBounds(10, 340, 80, 30);

        lbDropDownVal7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal7.setText("Toatl Amount :");
        jPanel2.add(lbDropDownVal7);
        lbDropDownVal7.setBounds(90, 340, 110, 30);

        txtTotalAmt.setEditable(false);
        txtTotalAmt.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalAmt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotalAmt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel2.add(txtTotalAmt);
        txtTotalAmt.setBounds(200, 340, 100, 30);

        lbDropDownVal8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal8.setText("Total Discount :");
        jPanel2.add(lbDropDownVal8);
        lbDropDownVal8.setBounds(310, 340, 120, 30);

        txtTotalDisc.setEditable(false);
        txtTotalDisc.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalDisc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotalDisc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel2.add(txtTotalDisc);
        txtTotalDisc.setBounds(430, 340, 100, 30);

        lbDropDownVal9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal9.setText("Inv. Amt :");
        jPanel2.add(lbDropDownVal9);
        lbDropDownVal9.setBounds(550, 340, 80, 30);

        txttotalFinalAmount.setEditable(false);
        txttotalFinalAmount.setBackground(new java.awt.Color(255, 255, 255));
        txttotalFinalAmount.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txttotalFinalAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel2.add(txttotalFinalAmount);
        txttotalFinalAmount.setBounds(620, 330, 160, 50);
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(310, 460, 230, 10);

        txtCustName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtCustName);
        txtCustName.setBounds(30, 90, 190, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Name");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 60, 130, 30);

        labdate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labdate1.setText("Date");
        jPanel2.add(labdate1);
        labdate1.setBounds(30, 0, 80, 30);

        txtDate.setEditable(false);
        txtDate.setBackground(new java.awt.Color(255, 255, 255));
        txtDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtDate);
        txtDate.setBounds(30, 30, 190, 30);
        jPanel2.add(jSeparator6);
        jSeparator6.setBounds(10, 380, 770, 10);
        jPanel2.add(jSeparator7);
        jSeparator7.setBounds(10, 460, 230, 10);

        lbDropDownVal14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDropDownVal14.setText("Item *");
        jPanel2.add(lbDropDownVal14);
        lbDropDownVal14.setBounds(280, 380, 90, 30);

        txtBarCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBarCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBarCodeFocusLost(evt);
            }
        });
        jPanel2.add(txtBarCode);
        txtBarCode.setBounds(120, 480, 450, 30);

        labdate2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labdate2.setText("BarCode");
        jPanel2.add(labdate2);
        labdate2.setBounds(30, 480, 80, 30);

        add(jPanel2);
        jPanel2.setBounds(0, 0, 790, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        searchItem();
    }//GEN-LAST:event_btnSearchActionPerformed

    public void searchItem() {
        boolean check = true;
        if ((txtBarCode.getText() == null || txtBarCode.getText().trim().length() == 0) && (ddItems.getSelectedItem() == null || ddItems.getSelectedItem().toString().equalsIgnoreCase("select"))) {
            check = false;
            JOptionPane.showMessageDialog(this, "Please select Item or enter bar code");
        }
        if (check) {
            long itId = 0;
            String barcode = null;
            if (ddItems.getSelectedItem() != null && !ddItems.getSelectedItem().toString().equalsIgnoreCase("select")) {
                String s[] = ddItems.getSelectedItem().toString().split("-");
                itId = Long.parseLong(s[s.length - 1]);
            } else {
                barcode = txtBarCode.getText().trim();
            }
            ItemsDao itmd = new ItemsDao();
            List<Items> ils = itmd.getItems(itId, null, null, barcode);
            if (!ils.isEmpty()) {
                items = ils.get(0);
                txtAddItemBrand.setText(items.getBrandId().getBrandName());
                txtAddItemCode.setText(items.getItemCode());
                txtAddItemName.setText(items.getItemName());
                txtPrice.setText(items.getPrice() + "");
                txtQuantity.setText("0");
                txtQuantity.setFocusable(true);
                pnlAddItems.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No Item Found");
            }
        }
    }

    public void addToCart() {
        boolean check = true;
        int qty = 0;
        if (txtQuantity.getText() == null || txtQuantity.getText().trim().length() == 0) {
            check = false;
            JOptionPane.showMessageDialog(this, "Quantity Requred");
        } else {
            try {
                qty = Integer.parseInt(txtQuantity.getText().toString());
                if (qty <= 0) {
                    check = false;
                    JOptionPane.showMessageDialog(this, "Quantity should be greater than 0");
                }
            } catch (Exception e) {
                check = false;
                JOptionPane.showMessageDialog(this, "Invalid Quantity");
            }
        }
        if (check) {
            SalesItems p = new SalesItems();
            p.setSrNo(srNo++);
            p.setItems(items);
            p.setQuantity(qty);
            p.setPrice(p.getItems().getPrice());
            p.setAmount(qty * p.getItems().getPrice());
            p.setDiscount(calDiscount(p.getAmount()));
            p.setTotalAmount(p.getAmount() - p.getDiscount());
            p.setItemNumber(txtSerialNo.getText());
            salesItems.add(p);
            pnlAddItems.setVisible(false);
            clearAddFields();
            showTableData();
        }
    }

    public double calDiscount(double amount) {
        double dis = 0;
        if (ddIDiscount.getSelectedItem() != null && !ddIDiscount.getSelectedItem().toString().equalsIgnoreCase("Select")) {
            dis = (amount / 100) * (Double.parseDouble(ddIDiscount.getSelectedItem().toString()));
        }
        return dis;
    }

    private void ddBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddBrandActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        clearAll();
        clearAddFields();
        clearHeaderFields();
        sales = new Sales();
    }//GEN-LAST:event_btnImportActionPerformed

    public void clearHeaderFields() {
        txtMobileNo.setText("");
        txtCustName.setText("");
        txtAddess.setText("");
    }

    public void clearAll() {
        salesItems = new ArrayList<>();
        srNo = 1;
        showTableData();
    }

    public void clearAddFields() {
        ddBrand.setSelectedItem("Selec");
        ddItems.setSelectedItem("Select");
        txtPrice.setText("0");
        txtQuantity.setText("0");
        txtAmount.setText("0");
        ddIDiscount.setSelectedItem("Select");
        txtFinalAmount.setText("0");
    }

    private void ddItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddItemsActionPerformed
        // searchItem();
    }//GEN-LAST:event_ddItemsActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        clearAddFields();
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        ItemsDao id = new ItemsDao();
        sales.setInvoiceNo(id.getInvoiceNo());
        String msg = id.saveSales(sales);
        if (msg.equalsIgnoreCase("success")) {
            if (true) {
                pnlInvoice.setTitle(" Invoice : " + sales.getInvoiceNo());
                String con = ReadCSV.generateInvoiceBill(sales);
                System.err.println("Con " + con);
                htmlContent.setText(con);
                pnlInvoice.setVisible(true);
            } else {
                File f = OrderPDF.salesPdf(sales);
                try {
                    if (f.exists()) {
                        Process p;
                        p = Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + f.getAbsolutePath());
                        p.waitFor();
                    }
                } catch (Exception e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
            pnlConfirmation.setVisible(false);
            clearAll();
        } else {
            JOptionPane.showMessageDialog(this, msg);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void ddBrandItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddBrandItemStateChanged
        if (ddBrand.getSelectedItem() != null && !ddBrand.getSelectedItem().toString().equalsIgnoreCase("select")) {
            ddItems.setModel(new javax.swing.DefaultComboBoxModel(GeneralUtil.getItemeArray("Select", ddBrand.getSelectedItem().toString())));
        } else {
            ddItems.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Select"}));
        }
    }//GEN-LAST:event_ddBrandItemStateChanged

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        this.homePanel.openSalesList(menuName);
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void btnImport3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImport3ActionPerformed

        if (txtMobileNo.getText() != null && txtMobileNo.getText().trim().length() > 0) {
            if (!salesItems.isEmpty()) {
                sales = new Sales();
                sales.setCustMobileNo(txtMobileNo.getText());
                sales.setCustName(txtCustName.getText());
                sales.setCustAddress(txtAddess.getText());
                sales.setCustMobileNo(txtMobileNo.getText());
                sales.setCreatedBy(homePanel.getMainWindow().getUsers().getUserId());
                sales.setStatus("active");
                sales.setAmount(Double.parseDouble(txtTotalAmt.getText()));
                sales.setTotalAmount(Double.parseDouble(txttotalFinalAmount.getText()));
                sales.setDiscount(Double.parseDouble(txtTotalDisc.getText()));
                sales.setCreatedOn(new Date());
                sales.setSalesItems(salesItems);
                lbItemCount.setText(salesItems.size() + "");
                lbDisc.setText(sales.getDiscount() + "");
                lbFnTot.setText(sales.getTotalAmount() + "");
                lbAmount.setText(sales.getAmount() + "");
                Object[][] cod = new Object[salesItems.size()][4];
                int i = 0;
                for (SalesItems s : salesItems) {
                    cod[i][0] = s.getItems().getItemName();
                    cod[i][1] = s.getQuantity();
                    cod[i][2] = s.getDiscount();
                    cod[i][3] = s.getTotalAmount();
                    i++;
                }
                tabConfirmation.setModel(new javax.swing.table.DefaultTableModel(
                        cod,
                        new String[]{
                            "Item", "Quantity", "Discount", "Amount"
                        }
                ));
                pnlConfirmation.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Please add Items");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Purchare No. Required");
        }
    }//GEN-LAST:event_btnImport3ActionPerformed

    private void ddIDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddIDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddIDiscountActionPerformed

    private void btnSearch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch3ActionPerformed
        if (tbPurItems.getSelectedColumnCount() > 0) {
            int sr = Integer.parseInt(tbPurItems.getValueAt(tbPurItems.getSelectedRow(), 0).toString());
            for (int i = 0; i < salesItems.size(); i++) {
                if (salesItems.get(i).getSrNo() == sr) {
                    salesItems.remove(i);
                    break;
                }
            }
            showTableData();
        } else {
            JOptionPane.showMessageDialog(this, "Please select row for delete");
        }

    }//GEN-LAST:event_btnSearch3ActionPerformed

    private void ddItemsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddItemsItemStateChanged
        if (ddItems.getSelectedItem() != null && !ddItems.getSelectedItem().toString().equalsIgnoreCase("Select")) {
            String s[] = ddItems.getSelectedItem().toString().split("-");
            long itId = Long.parseLong(s[s.length - 1]);
            ItemsDao itmd = new ItemsDao();
            txtPrice.setText(itmd.getItems(itId, null, null).get(0).getPrice() + "");
            calculateAmount();
        }

    }//GEN-LAST:event_ddItemsItemStateChanged

    private void txtQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusLost
        System.err.println("Hi Hi ");
        calculateAmount();
    }//GEN-LAST:event_txtQuantityFocusLost

    private void ddIDiscountItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddIDiscountItemStateChanged
        calculateAmount();
    }//GEN-LAST:event_ddIDiscountItemStateChanged

    private void btnConfirmCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmCloseActionPerformed
        pnlConfirmation.setVisible(false);
    }//GEN-LAST:event_btnConfirmCloseActionPerformed

    private void btnAddItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemCloseActionPerformed
        pnlAddItems.setVisible(false);
    }//GEN-LAST:event_btnAddItemCloseActionPerformed

    private void btnAdditem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdditem1ActionPerformed
        addToCart();
    }//GEN-LAST:event_btnAdditem1ActionPerformed

    private void txtAddItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddItemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddItemCodeActionPerformed

    private void txtAddItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddItemNameActionPerformed

    private void txtAddItemBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddItemBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddItemBrandActionPerformed

    private void txtBarCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBarCodeFocusLost
        searchItem();
    }//GEN-LAST:event_txtBarCodeFocusLost

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            htmlContent.print();  
             this.homePanel.openSalesList(menuName);// TODO add your handling code here:
        } catch (PrinterException ex) {

        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnCSV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSV4ActionPerformed
        this.homePanel.openSalesList(menuName);
    }//GEN-LAST:event_btnCSV4ActionPerformed

    private void pnlInvoiceWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_pnlInvoiceWindowDeactivated
          this.homePanel.openSalesList(menuName);
    }//GEN-LAST:event_pnlInvoiceWindowDeactivated

    public void calculateAmount() {
        try {
            int qty = Integer.parseInt(txtQuantity.getText());
            double price = Double.parseDouble(txtPrice.getText());
            double amt = qty * price;
            txtAmount.setText(amt + "");
            double dis = calDiscount(amt);
            txtDiscount.setText(dis + "");
            txtFinalAmount.setText((amt - dis) + "");
        } catch (Exception e) {
            txtAmount.setText("0");
            txtFinalAmount.setText("0");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItemClose;
    private javax.swing.JButton btnAdditem1;
    private javax.swing.JButton btnCSV4;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnConfirmClose;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnImport3;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JButton btnSearch3;
    private javax.swing.JComboBox ddBrand;
    private javax.swing.JComboBox ddIDiscount;
    private javax.swing.JComboBox ddItems;
    private javax.swing.JTextPane htmlContent;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel labdate;
    private javax.swing.JLabel labdate1;
    private javax.swing.JLabel labdate2;
    private javax.swing.JLabel lbAmount;
    private javax.swing.JLabel lbDisc;
    private javax.swing.JLabel lbDropDownVal;
    private javax.swing.JLabel lbDropDownVal10;
    private javax.swing.JLabel lbDropDownVal11;
    private javax.swing.JLabel lbDropDownVal12;
    private javax.swing.JLabel lbDropDownVal13;
    private javax.swing.JLabel lbDropDownVal14;
    private javax.swing.JLabel lbDropDownVal15;
    private javax.swing.JLabel lbDropDownVal16;
    private javax.swing.JLabel lbDropDownVal2;
    private javax.swing.JLabel lbDropDownVal3;
    private javax.swing.JLabel lbDropDownVal4;
    private javax.swing.JLabel lbDropDownVal5;
    private javax.swing.JLabel lbDropDownVal6;
    private javax.swing.JLabel lbDropDownVal7;
    private javax.swing.JLabel lbDropDownVal8;
    private javax.swing.JLabel lbDropDownVal9;
    private javax.swing.JLabel lbFnTot;
    private javax.swing.JLabel lbItemCount;
    private javax.swing.JDialog pnlAddItems;
    private javax.swing.JDialog pnlConfirmation;
    private javax.swing.JDialog pnlInvoice;
    private javax.swing.JTable tabConfirmation;
    private javax.swing.JTable tbPurItems;
    private javax.swing.JTextField txtAddItemBrand;
    private javax.swing.JTextField txtAddItemCode;
    private javax.swing.JTextField txtAddItemName;
    private javax.swing.JTextField txtAddess;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBarCode;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtFinalAmount;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSerialNo;
    private javax.swing.JTextField txtTotalAmt;
    private javax.swing.JTextField txtTotalDisc;
    private javax.swing.JTextField txttotalFinalAmount;
    // End of variables declaration//GEN-END:variables

}
