/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbconnection;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author celstra31
 */
public class MyWindow extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form MyWindow
     */
    public MyTestClass myTestClass;
    private Timer timer;

    public MyWindow() {
        myTestClass = new MyTestClass();
        initComponents();
        jPanel2.setVisible(false);
        txtFileLocation.setEditable(false);
        txtNewSchemaName.setText("AQUA");
        txtNewPassword.setText("AQUA");
        txtNewSchemaUrl.setText("localhost");
        txtNewSid.setText("orcl");
        chMenuItems.setSelected(false);
        txtOldSchemaName.setText("mycart");
        txtOldPassword.setText("mycart");
        txtOldSchemaUrl.setText("localhost");
        txtOldSid.setText("orcl");
        txtFileLocation.setText("D:\\1\\sysadmin");
        timer = new Timer(100, new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                System.out.println(myTestClass.getProText() + " :  " + myTestClass.getProgressCount());
                int per = (int) 3.5 * myTestClass.getProgressCount();
                if (per > 100) {
                    per = 100;
                }
                jProgressBar1.setValue(per);
                jProHeader.setText(myTestClass.getProText() + " -- " + per + "%");

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        txtNewSchemaName = new javax.swing.JTextField();
        txtOldSchemaUrl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNewSchemaUrl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOldSchemaName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtFileLocation = new javax.swing.JTextField();
        txtNewSid = new javax.swing.JTextField();
        txtOldPassword = new javax.swing.JTextField();
        txtOldPort = new javax.swing.JTextField();
        txtOldSid = new javax.swing.JTextField();
        txtNewPort = new javax.swing.JTextField();
        txtNewPassword = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        chIndexes = new javax.swing.JCheckBox();
        chForeignKey = new javax.swing.JCheckBox();
        chViews = new javax.swing.JCheckBox();
        chMaterializedViews = new javax.swing.JCheckBox();
        chProcedure = new javax.swing.JCheckBox();
        chMenuItems = new javax.swing.JCheckBox();
        chTable = new javax.swing.JCheckBox();
        chSequence = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jCheckBoxAll = new javax.swing.JCheckBox();
        chFunctions = new javax.swing.JCheckBox();
        txtPrefixSchema = new javax.swing.JTextField();
        jProHeader = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DBConnection");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setToolTipText("");

        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        jFileChooser1.setOpaque(true);
        jFileChooser1.setPreferredSize(new java.awt.Dimension(640, 310));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        jPanel2.add(jFileChooser1);
        jFileChooser1.getAccessibleContext().setAccessibleParent(jPanel2);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 650, 330);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("New Schema Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 70, 150, 25);

        txtNewSchemaName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtNewSchemaName);
        txtNewSchemaName.setBounds(180, 70, 170, 25);

        txtOldSchemaUrl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtOldSchemaUrl.setText("192.168.1.230");
        jPanel1.add(txtOldSchemaUrl);
        txtOldSchemaUrl.setBounds(180, 110, 170, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Old Schema URL");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 110, 150, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("New Schema URL");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 40, 150, 25);

        txtNewSchemaUrl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNewSchemaUrl.setText("192.168.1.156");
        jPanel1.add(txtNewSchemaUrl);
        txtNewSchemaUrl.setBounds(180, 40, 170, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("File Location");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 180, 150, 25);

        txtOldSchemaName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtOldSchemaName);
        txtOldSchemaName.setBounds(180, 140, 170, 25);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(500, 350, 100, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(360, 350, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Old Schema Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(22, 140, 150, 25);
        jPanel1.add(txtFileLocation);
        txtFileLocation.setBounds(180, 180, 320, 25);

        txtNewSid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNewSid.setText("xe");
        jPanel1.add(txtNewSid);
        txtNewSid.setBounds(520, 40, 70, 25);

        txtOldPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtOldPassword);
        txtOldPassword.setBounds(360, 140, 140, 25);

        txtOldPort.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtOldPort.setText("1521");
        jPanel1.add(txtOldPort);
        txtOldPort.setBounds(360, 110, 140, 25);

        txtOldSid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtOldSid.setText("xe");
        jPanel1.add(txtOldSid);
        txtOldSid.setBounds(520, 110, 70, 25);

        txtNewPort.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNewPort.setText("1521");
        jPanel1.add(txtNewPort);
        txtNewPort.setBounds(360, 40, 140, 25);

        txtNewPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtNewPassword);
        txtNewPassword.setBounds(360, 70, 140, 25);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Browse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(520, 180, 100, 30);

        chIndexes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chIndexes.setSelected(true);
        chIndexes.setText("Indexes");
        jPanel1.add(chIndexes);
        chIndexes.setBounds(370, 250, 110, 25);

        chForeignKey.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chForeignKey.setSelected(true);
        chForeignKey.setText("Foreign Key");
        jPanel1.add(chForeignKey);
        chForeignKey.setBounds(510, 250, 100, 25);

        chViews.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chViews.setSelected(true);
        chViews.setText("Views");
        jPanel1.add(chViews);
        chViews.setBounds(40, 280, 120, 25);

        chMaterializedViews.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chMaterializedViews.setSelected(true);
        chMaterializedViews.setText("Materialized Views");
        jPanel1.add(chMaterializedViews);
        chMaterializedViews.setBounds(180, 280, 170, 25);

        chProcedure.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chProcedure.setSelected(true);
        chProcedure.setText("Procedure");
        jPanel1.add(chProcedure);
        chProcedure.setBounds(370, 280, 130, 25);

        chMenuItems.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chMenuItems.setSelected(true);
        chMenuItems.setText("Menu Items");
        jPanel1.add(chMenuItems);
        chMenuItems.setBounds(510, 280, 110, 25);

        chTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chTable.setSelected(true);
        chTable.setText("Tables");
        jPanel1.add(chTable);
        chTable.setBounds(180, 250, 170, 25);

        chSequence.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chSequence.setSelected(true);
        chSequence.setText("Sequence");
        jPanel1.add(chSequence);
        chSequence.setBounds(40, 250, 130, 25);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(80, 230, 550, 2);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(30, 338, 600, 10);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(30, 230, 10, 110);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(630, 230, 10, 110);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(30, 230, 10, 10);

        jCheckBoxAll.setSelected(true);
        jCheckBoxAll.setText("All");
        jCheckBoxAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAllActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxAll);
        jCheckBoxAll.setBounds(40, 220, 60, 25);

        chFunctions.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chFunctions.setSelected(true);
        chFunctions.setText("Functions");
        jPanel1.add(chFunctions);
        chFunctions.setBounds(40, 310, 110, 25);
        jPanel1.add(txtPrefixSchema);
        txtPrefixSchema.setBounds(180, 350, 160, 30);

        jProHeader.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jProHeader.setText("Pending -- 0%");
        jPanel1.add(jProHeader);
        jProHeader.setBounds(20, 380, 460, 30);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(20, 410, 590, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Prefix Schema Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 350, 160, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtNewSchemaName.setText("");
        txtNewSchemaUrl.setText("");
        txtOldSchemaName.setText("");
        txtOldSchemaUrl.setText("");
        txtFileLocation.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    int barzise = 0;
    String oldUrl = "";
    String newUrl = "";
    Set<String> set = new HashSet<String>();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        oldUrl = "jdbc:oracle:thin:@" + txtOldSchemaUrl.getText() + ":" + txtOldPort.getText() + "/" + txtOldSid.getText();
        newUrl = "jdbc:oracle:thin:@" + txtNewSchemaUrl.getText() + ":" + txtNewPort.getText() + "/" + txtNewSid.getText();
        System.out.println("oldUrl : " + oldUrl);
        System.out.println("newUrl : " + newUrl);

        if (chTable.isSelected()) {
            set.add("Tables");
        }
        if (chIndexes.isSelected()) {
            set.add("Indexes");
        }
        if (chForeignKey.isSelected()) {
            set.add("ForeignKey");
        }
        if (chViews.isSelected()) {
            set.add("Views");
        }
        if (chMenuItems.isSelected()) {
            set.add("MenuItems");
        }
        if (chProcedure.isSelected()) {
            set.add("Procedure");
        }
        if (chMaterializedViews.isSelected()) {
            set.add("MaterializedViews");
        }

        if (chSequence.isSelected()) {
            set.add("Sequence");
        }

        if (chFunctions.isSelected()) {
            set.add("Function");
        }
        barzise = 100 / set.size();
        jButton1.setEnabled(false);
        myTestClass.setProText("Pending");
        myTestClass.setProgressCount(0);

        jProgressBar1.setValue(0);
        jProHeader.setText("Pending -- 0%");
        System.out.println("barzise : " + barzise);
        timer.start();
        Thread thread = new Thread(this);
        thread.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void run() {
        String msg = myTestClass.generateScript(newUrl, this.txtNewSchemaName.getText(), this.txtNewPassword.getText(), oldUrl, this.txtOldSchemaName.getText(), this.txtOldPassword.getText(), this.txtFileLocation.getText(), set, txtPrefixSchema.getText());
        if (msg.equalsIgnoreCase("success")) {
            timer.stop();
            jButton1.setEnabled(true);
            jProgressBar1.setValue(100);
            jProHeader.setText("Completed -- 100%");
            JOptionPane.showMessageDialog(this.jPanel1, msg, "SUCCESS", 1);
        } else {
            timer.stop();
            jButton1.setEnabled(true);
            jProgressBar1.setValue(0);
            jProHeader.setText("Pending -- 0%");
            JOptionPane.showMessageDialog(this.jPanel1, msg, "ERROR", 0);
        }
    }


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        jPanel2.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        try {
            txtFileLocation.setText(jFileChooser1.getSelectedFile().getPath());
        } catch (Exception e) {

        }
        jPanel2.setVisible(false);
        jPanel1.repaint();
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jCheckBoxAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAllActionPerformed
        chIndexes.setSelected(jCheckBoxAll.isSelected());
        chForeignKey.setSelected(jCheckBoxAll.isSelected());
        chViews.setSelected(jCheckBoxAll.isSelected());
        chMaterializedViews.setSelected(jCheckBoxAll.isSelected());
        chProcedure.setSelected(jCheckBoxAll.isSelected());
        chMenuItems.setSelected(jCheckBoxAll.isSelected());
        chTable.setSelected(jCheckBoxAll.isSelected());
        chSequence.setSelected(jCheckBoxAll.isSelected());
        chFunctions.setSelected(jCheckBoxAll.isSelected());
    }//GEN-LAST:event_jCheckBoxAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chForeignKey;
    private javax.swing.JCheckBox chFunctions;
    private javax.swing.JCheckBox chIndexes;
    private javax.swing.JCheckBox chMaterializedViews;
    private javax.swing.JCheckBox chMenuItems;
    private javax.swing.JCheckBox chProcedure;
    private javax.swing.JCheckBox chSequence;
    private javax.swing.JCheckBox chTable;
    private javax.swing.JCheckBox chViews;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBoxAll;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jProHeader;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField txtFileLocation;
    private javax.swing.JTextField txtNewPassword;
    private javax.swing.JTextField txtNewPort;
    private javax.swing.JTextField txtNewSchemaName;
    private javax.swing.JTextField txtNewSchemaUrl;
    private javax.swing.JTextField txtNewSid;
    private javax.swing.JTextField txtOldPassword;
    private javax.swing.JTextField txtOldPort;
    private javax.swing.JTextField txtOldSchemaName;
    private javax.swing.JTextField txtOldSchemaUrl;
    private javax.swing.JTextField txtOldSid;
    private javax.swing.JTextField txtPrefixSchema;
    // End of variables declaration//GEN-END:variables
}
