/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Jul 26, 2014, 6:58:54 PM
 */

package com.hes.view;

import com.hes.pojo.UserLogin;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author SATISH SYAMALA
 */
public class MainWindow extends javax.swing.JFrame  implements ActionListener {

    static int hei = 0;
    static int wid = 0;
    Timer time = new Timer(50, this);
    LoginPanel loginPanel = null;
    HomePanel homePanel = null;
    private UserLogin userLogin;

    public MainWindow() {
        initComponents();
        mainPanel.setLocation((wid - 1024) / 2, (hei - 768) / 2);
        loginPanel = new LoginPanel(this);
        loginPanel.setBounds(0, 0, 1024, 768);
        loginPanel.setVisible(true);
        mainPanel.add(loginPanel);

        homePanel = new HomePanel(this);
        homePanel.setBounds(0, 0, 1024, 768);
        homePanel.setVisible(false);
        mainPanel.add(homePanel);
        mainPanel.repaint();
        
       
    }

     public void showLoginPanel() {
        homePanel.setVisible(false);
        loginPanel.setVisible(true);
        loginPanel.inital();
    }

      public void showHomePanel() {
        loginPanel.setVisible(false);
        homePanel.initail(this);
        homePanel.setVisible(true);
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setTitle("HES");
        setUndecorated(true);
        getContentPane().setLayout(null);

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainPanel.setLayout(null);
        getContentPane().add(mainPanel);
        mainPanel.setBounds(50, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        Dimension screnn = Toolkit.getDefaultToolkit().getScreenSize();
        hei = screnn.height;
        wid = screnn.width;
        MainWindow mwf = new MainWindow();
        mwf.setBounds(0, 0, wid, hei);
        mwf.setVisible(true);
    }

    public void actionPerformed(ActionEvent e) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the userLogin
     */
    public UserLogin getUserLogin() {
        return userLogin;
    }

    /**
     * @param userLogin the userLogin to set
     */
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }

}
