/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportPanel.java
 *
 * Created on Aug 3, 2014, 11:38:35 AM
 */
package com.hes.view;

import com.hes.model.ReportModel;
import com.hes.pojo.Customer;
import com.hes.pojo.Invoice;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author SATISH SYAMALA
 */
public class ReportPanel extends javax.swing.JPanel {

    HomePanel homePanel = null;
    private List<Customer> customers = null;
    ReportModel reportModel = new ReportModel();
    JXDatePicker dateFrom = new JXDatePicker();
    JXDatePicker dateTo = new JXDatePicker();
    List<Invoice> invoices = null;
    SimpleDateFormat sd = new SimpleDateFormat("dd-MM-yyyy");

    public ReportPanel() {
        initComponents();

        dateFrom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dateFrom.setFormats("dd-MM-yyyy");
        dateFrom.setDate(new Date());
        dateFrom.setBounds(80, 60, 170, 25);
        pnReport.add(dateFrom);

        dateTo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dateTo.setFormats("dd-MM-yyyy");
        dateTo.setDate(new Date());
        dateTo.setBounds(360, 60, 190, 25);
        pnReport.add(dateTo);


    }

    public void init(HomePanel homePanel) {
        this.homePanel = homePanel;
        customers = reportModel.getCustomerList();
        String[] sList = new String[customers.size() + 1];
        sList[0] = "----All----";
        for (int i = 0; i < customers.size(); i++) {
            Customer sp = customers.get(i);
            sList[i + 1] = sp.getName();
        }
        dateFrom.setDate(new Date());
        dateTo.setDate(new Date());
        cbmCustomer.setModel(new javax.swing.DefaultComboBoxModel(sList));
        invoices = new ArrayList<Invoice>();
        setInvoiceData();

    }

    public void setInvoiceData() {
        Object[][] data = new Object[invoices.size() + 1][6];
        double total = 0.0;
        double disc = 0.0;
        for (int i = 0; i < invoices.size(); i++) {
            Invoice cm = invoices.get(i);
            data[i][0] = (i + 1) + "";
            data[i][1] = cm.getInvoiceNumber();
            data[i][2] = cm.getCustname();
            data[i][3] = (cm.getInvoiceType() == 1) ? "CST Or VAT" : "Endorsement";
            data[i][4] = sd.format(cm.getInvoiceDate());

            data[i][5] = cm.getGrandTotal();
            disc += cm.getFinalDiscount();
            total += cm.getGrandTotal();
        }
        if (!invoices.isEmpty()) {
            data[invoices.size()][0] = "";
            data[invoices.size()][1] = "";
            data[invoices.size()][2] = "";
            data[invoices.size()][3] = "";
            data[invoices.size()][4] = "Total";

            data[invoices.size()][5] = total;
        }
        setTableDate(data);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnReport = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbmCustomer = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setOpaque(false);
        setLayout(null);

        pnReport.setOpaque(false);
        pnReport.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("From ");
        pnReport.add(jLabel1);
        jLabel1.setBounds(20, 60, 40, 25);

        cbmCustomer.setFont(new java.awt.Font("Tahoma", 1, 14));
        cbmCustomer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbmCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmCustomerActionPerformed(evt);
            }
        });
        pnReport.add(cbmCustomer);
        cbmCustomer.setBounds(120, 20, 360, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Customer ");
        pnReport.add(jLabel2);
        jLabel2.setBounds(20, 20, 90, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("To");
        pnReport.add(jLabel3);
        jLabel3.setBounds(310, 60, 30, 25);
        pnReport.add(jSeparator2);
        jSeparator2.setBounds(10, 100, 750, 2);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnReport.add(jButton1);
        jButton1.setBounds(659, 540, 100, 30);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sr.No", "Invoice No", "Invoice Type", "Date", "Discont", "Toatal Amont"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(4).setResizable(false);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(5).setResizable(false);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);

        pnReport.add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 760, 420);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("REPORT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnReport.add(jButton2);
        jButton2.setBounds(650, 60, 100, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("VIEW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnReport.add(jButton3);
        jButton3.setBounds(543, 540, 100, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 204));
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnReport.add(jButton4);
        jButton4.setBounds(430, 540, 100, 30);

        add(pnReport);
        pnReport.setBounds(0, 0, 790, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void cbmCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmCustomerActionPerformed
    String custName = "";
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int index = cbmCustomer.getSelectedIndex();

        if (index > 0) {
            custName = customers.get(index - 1).getName();
        }
        if (dateFrom.getDate().after(dateTo.getDate())) {
            JOptionPane.showMessageDialog(pnReport, "From date before To date");
        } else {
            invoices = reportModel.getInvoiceDetails(custName, dateFrom.getDate(), dateTo.getDate());
            setInvoiceData();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            jTable1.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(pnReport, "No Printer Connection");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTable1.getSelectedRow() < invoices.size()) {
            if (jTable1.getSelectedRowCount() > 0) {
                reportModel.generateBills(invoices.get(jTable1.getSelectedRow()));
            } else {
                JOptionPane.showMessageDialog(pnReport, "Please select row for to view invoice details");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jTable1.getSelectedRow() < invoices.size()) {
            if (jTable1.getSelectedRowCount() > 0) {
                String msg = reportModel.deleteInvoice(invoices.get(jTable1.getSelectedRow()));
                if (msg.equals("ok")) {
                    invoices = reportModel.getInvoiceDetails(custName, dateFrom.getDate(), dateTo.getDate());
                    setInvoiceData();
                }
            } else {
                JOptionPane.showMessageDialog(pnReport, "Please select row for Delete invoice details");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbmCustomer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnReport;
    // End of variables declaration//GEN-END:variables

    private void setTableDate(Object[][] data) {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                data,
                new String[]{
                    "Sr.No", "Invoice No", "Customer", "Invoice Type", "Date", "Toatal Amont"
                }) {

            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });



        jScrollPane1.setViewportView(jTable1);

        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(4).setResizable(false);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(5).setResizable(false);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
    }
}
